version: '3.3'
services:
  web:
    image: web:latest
    container_name: web
    volumes:
      - /home/ubuntu/myproject/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/myproject/server.crt:/etc/nginx/files/server.crt
      - /home/ubuntu/myproject/server.key:/etc/nginx/files/server.key
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - custom_net

  api:
    image: api:latest
    container_name: api
    environment:
      - CHATGPT_APIKEY=${CHATGPT_APIKEY}
    restart: always
    networks:
      - custom_net

networks:
  custom_net:
    external:
      name: myproject
